#!/bin/sh

### BEGIN INIT INFO
# Provides:             longview
# Required-Start:       $network $local_fs
# Required-Stop:        $network $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Longview Monitoring Agent
### END INIT INFO

set -e

umask 022

DAEMON="/opt/linode/longview/Linode/Longview.pl"
PID="/var/run/longview.pid"
. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting Longview Agent" "longview"
		if start-stop-daemon --start -p $PID --startas $DAEMON 2>/dev/null; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
		;;
	debug)
		log_daemon_msg "Starting Longview Agent (With Debug Flag)" "longview"
		if start-stop-daemon --start -p $PID --startas $DAEMON Debug 2>/dev/null; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
		;;
	stop)
		log_daemon_msg "Stopping Longview Agent" "longview"
		if start-stop-daemon --stop --quiet -p $PID 2>/dev/null; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
		;;
	restart)
		log_daemon_msg "Restarting Longview Agent" "longview"
		start-stop-daemon --stop --quiet --oknodo --retry 30 -p /var/run/longview.pid
		if start-stop-daemon --start -p $PID --startas $DAEMON 2>/dev/null; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
		;;
	reload|force-reload)
		log_daemon_msg "Restarting Longview Agent" "longview"
		if start-stop-daemon --stop --quiet --oknodo --signal HUP -p /var/run/longview.pid; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
		;;
	status)
		status_of_proc -p $PID $DAEMON longview && exit 0 || exit $?
		;;
	*)
		log_action_msg "Usage: /etc/init.d/longview {start|stop|restart|force-reload|reload|status}"
		exit 1
esac

exit 0